In [11]:
# Loading the dataset using pandas

import numpy as np 
import pandas as pd

In [12]:
df=pd.read_csv('customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [13]:
# Imputing missing values in Review Rating column with the median rating of the product category
df["Review Rating"]=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [14]:
# Renaming columns according to snake casing for better readability and documentation
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(" ","_")

In [15]:
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [16]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [17]:
#create a new column age_group
labels=['Young_Adult','Adult','Middle_aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [18]:
df[["age","age_group"]].head(10)

   age    age_group
0   55  Middle_aged
1   19  Young_Adult
2   50  Middle_aged
3   21  Young_Adult
4   45  Middle_aged
5   46  Middle_aged
6   63       Senior
7   27  Young_Adult
8   26  Young_Adult
9   57  Middle_aged

In [19]:
# create new column purchase_frequency_days
feature_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchase_frequency']=df['frequency_of_purchases'].map(feature_mapping)

In [20]:
df[['purchase_frequency','frequency_of_purchases']].head(10)

   purchase_frequency frequency_of_purchases
0                  14            Fortnightly
1                  14            Fortnightly
2                   7                 Weekly
3                   7                 Weekly
4                 365               Annually
5                   7                 Weekly
6                  90              Quarterly
7                   7                 Weekly
8                 365               Annually
9                  90              Quarterly

In [21]:
# Dropping promo code used column
df=df.drop("promo_code_used",axis=1)

In [22]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle_aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young_Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle_aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young_Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle_aged,365

In [24]:
#Connecting Python script to PostgreSQL

In [ ]:
pip install psycopg2-binary sqlalchemy

In [17]:
from sqlalchemy import create_engine

username="Your USERNAME"
password="YOUR PASSWORD"
host="LOCALHOST"
port="YOUR PORT"
database="Customer_behaviour"

engine= create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name="customer"
df.to_sql(table_name,engine,if_exists="replace",index=False)

print(f"Data successfully loaded into table'{table_name}'in database'{database}'")

Data successfully loaded into table'customer'in database'Customer_behaviour'